version: '3.9'
services:
  php:
    container_name: webr4-php
    build:
      context: docker/php
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - '9696:80'
    volumes:
      - .:/var/www/html
      - /var/www/html/var
    networks:
      - dev
  db:
    container_name: webr4-db
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev
  phpmyadmin:
    container_name: webr4-phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - '6969:80'
    environment:
      PMA_HOST: db
    networks:
      - dev
networks:
  dev: